### ISSUE TITLE
[Feature Request] Use a GraphQL Subscription for command output

### ISSUE THREAD

**Issue by beeman** [nrwl/angular-console#129]
Currently the command output is retrieved by polling the GraphQL Query with a small interval. It probably makes sense to use a GraphQL Subscription to handle the output of the commands as it should save a lot of unneeded requests.

![image](https://user-images.githubusercontent.com/36491/43973897-15202784-9cd9-11e8-9614-05e65496fc46.png)

I'm happy to give a go at implementing this if it seems useful.

**Comment by mrmeku** [comment]
## Notes for this bug

### Documentation on how to invoke subscriptions in Apollo Client:
https://www.apollographql.com/docs/react/advanced/subscriptions.html#subscriptions-client
https://www.apollographql.com/docs/react/advanced/subscriptions.html

### Documentation on how to implement subscriptions on the server:
https://www.apollographql.com/docs/graphql-subscriptions/index.html

### All places which need updating:
https://github.com/nrwl/angular-console/search?q=pollInterval&unscoped_q=pollInterval

**Comment by mrmeku** [comment]
We have decided to sunset our electron release of console so that we can better focus on high quality editor extension. That being the case I'm going to sadly close this bug with no plans to resolve the ask. 

Our vscode extension UI is moving away from using graphql for the sake of speeding up initial render
