### ISSUE TITLE
[enhancement] - Alert or Widget - compare current dependencies with latest in npm

### ISSUE THREAD

**Issue by jerryorta-dev** [nrwl/angular-console#165]
This would be an alert or widget that shows when a project no longer has the latest of a dependency. 

For example, if your project is running `@angular/core@6.1.0` and `@angular/core@6.2.0` has been released -- the UX shows the developer this information. 

This would have to depend on the `package-lock.json` or `yarn.lock` files.

**Comment by mrmeku** [comment]
We have decided to sunset our electron release of console so that we can better focus on high quality editor extension. That being the case I'm going to sadly close this bug with no plans to resolve the ask. Within VSCode and other editors I think seperate plugins are better suited to performing this task
