### ISSUE TITLE
/usr/bin/env: 'node': No such file or directory (ubuntu)

### ISSUE THREAD

**Issue by goldenbearkin** [nrwl/angular-console#201]
when I try to new angular workspace, it shows below:
```
$ng new auth --collection=@schematics/angular
/usr/bin/env: 'node': No such file or directory
```
and I use nvm.

**Comment by patrickhousley** [comment]
I can confirm that if I start the app from the terminal, the `node` is found.

**Comment by alexeagle** [comment]
It would be nice for Angular Console to statically link the nodejs binary instead of relying on users to have already installed it.

**Comment by mrmeku** [comment]
We have no plans to add a statically linked version of nodejs as of right now. However, if anyone would want to add support for nvm via a PR that would be wonderful. I'm happy to provide any support that one would need to make the PR

**Comment by arjunyel** [comment]
For me at least Angular Console is working with nvm without launching it from the terminal, I have 11.8.0 aliased as the default

**Comment by MrCroft** [comment]
Just switched to Windows/WSL2. And, while the commands work from the terminal (using zsh), if I try to do it from the VSCode extension, I get the "No such file or directory" error.
I'm not sure how NX works, and why doesn't it use the system's default terminal (zsh). It wants to use bash, and it seems to look at the .profile file, where NVM_DIR isn't set. NVM_DIR is set in ~/.bashrc and in ~/.zshrc
After I add the NVM stuff in the ~/.profile file, then the VSCode extension also works.
But if I think about it, since it's set in ~/.bashrc, isn't that where bash looks? This is strange...

**Comment by lesauf** [comment]
> Just switched to Windows/WSL2. And, while the commands work from the terminal (using zsh), if I try to do it from the VSCode extension, I get the "No such file or directory" error. I'm not sure how NX works, and why doesn't it use the system's default terminal (zsh). It wants to use bash, and it seems to look at the .profile file, where NVM_DIR isn't set. NVM_DIR is set in ~/.bashrc and in ~/.zshrc After I add the NVM stuff in the ~/.profile file, then the VSCode extension also works. But if I think about it, since it's set in ~/.bashrc, isn't that where bash looks? This is strange...

Thanks. It works.
