### ISSUE TITLE
Create new workspace got stuck on babel/parser

### ISSUE THREAD

**Issue by BartNetJS** [nrwl/angular-console#254]
Create a new workspace with @nrlw/schematics
Asked for a babel/parser version:
![image](https://user-images.githubusercontent.com/4865355/46818308-35176100-cd81-11e8-99f2-382c2135b03b.png)

But I cannot enter and UI is stuck. I can only close the app, and start over again

**Comment by mrmeku** [comment]
Can you provide us with a bit more context about how this bug was produced? Specifically could you run `node -v` on your system? I'm interested in why @babel/parser couldn't choose a version for itself. 

There are two ways to address this bug. One is to ensure that you don't need to make such a selection during workspace creation, and the other is to enable keyboard events within our terminal.

**Comment by BartNetJS** [comment]
node version is 8.11.2
ng cli: 
![image](https://user-images.githubusercontent.com/4865355/46858368-75232600-ce0b-11e8-9a82-b47d3b2ad5d4.png)

anything else that can help you?

**Comment by BartNetJS** [comment]
closed by accident I think

**Comment by mrmeku** [comment]
@FrozenPandaz Do you know why a developer might be prompted to choose a version of @babel/parser when using ng new? Should we peg a particular version on our side?

**Comment by FrozenPandaz** [comment]
Hi @BartNetJS,

This _may_ have been caused if you were installing as `@babel` dependencies were being published. This should mean that the issue would only happen for _very_ brief times when package groups are being published.

.ie
`@babel` team is publishing their dependencies..
`@babel/template` depends on `@babel/parser` and is published first
In the middle of this process, a developer tries to install `@babel/template` but it points to a version of `@babel/parser` which has not been published yet.
`@babel/parser` is published a few minutes later and no one has the issue anymore because all the versions are there.

Is this still happening for you? If the issue no longer persists, this would likely be the case and it would be a rare issue.

**Comment by mrmeku** [comment]
I'm going to close this for now until we have more information
