### ISSUE TITLE
[enhancement]  allow hiding of the e2e projects

### ISSUE THREAD

**Issue by johnpapa** [nrwl/angular-console#271]
because it makes it harder to find the main projects, and if i want to get at the e2e, i can then check a box and show them again.
![image](https://user-images.githubusercontent.com/1202528/47115110-92049280-d22b-11e8-8745-2aa1430c38b2.png)

**Comment by bampakoa** [comment]
This has already been resolved if using Angular CLI version 8.x

**Comment by mrmeku** [comment]
We have decided to sunset our electron release of console so that we can better focus on high quality editor extension. That being the case I'm going to sadly close this bug with no plans to resolve the ask. 

@bampakoa Thanks for pointing that flow out :)
@johnpapa With our new VSCode UX flow, we now filter projects based on the architect commands they support. So I think that meets the description of the feature even. But if you have a different UX flow in mind or have critiques please reopen the bug and let me know!
