### ISSUE TITLE
'src/app' Folder Structure Arbitrarily Mandatory

### ISSUE THREAD

**Issue by danielkuhlwein** [nrwl/angular-console#305]
Angular Console doesn't seem to work with projects that don't adhere to style guide [04-08](https://angular.io/guide/styleguide#style-04-08), which places the root module in `src/app/` and all feature modules in subsequent folders.

Trying to generate a component in a project that doesn't use the `/app` root folder results in the error:

`Specified module 'SS.App/Shared/shared.module.ts' does not exist.
Looked in the following directories:
    /src/app/SS.App/Shared/shared.module.ts
    /src/app/SS.App/Shared
    /src/app/SS.App
    /src/app/MyComponent
    /src/app
    /src`

It doesn't work because it always looks under `src/app/` for your module. It would be nice if there was away to customize this.

**Comment by mrmeku** [comment]
We already support NX workspaces so I'm not sure that you're right about that directory structure being required. 

Have you set your `newProjectRoot` flag in your angular.json correctly?
Did you try specifing a module in the schematic which led to that error?

When you have more details please reopen the issue so that we can address it if its a bug on our end!

**Comment by danielkuhlwein** [comment]
Thanks @mrmeku!

### The error I was getting:
* Angular Console suggested module path couldn't be found
* It was checking under src/app
![screen shot 2018-11-09 at 10 01 42 am](https://user-images.githubusercontent.com/6547750/48277077-e522cd00-e406-11e8-98aa-d16cf1c088f5.png)

### What fixed it:
* Manually changing "src" -> ".."
![screen shot 2018-11-09 at 10 01 48 am](https://user-images.githubusercontent.com/6547750/48277146-008dd800-e407-11e8-8b3b-451639d39f9a.png)
