### ISSUE TITLE
Bundle Node with Angular Console

### ISSUE THREAD

**Issue by MrCroft** [nrwl/angular-console#540]
While using WSL (Windows Subsystem Linux), having Node installed on both the host OS (Windows) and on WSL can be very tricky. It usually results in npm not working properly.

Ideally, Angular Console should have the appropriate Node.js version bundled in and not require us to have Node.js installed on the host OS.
As a nice side-effect, this would also make Angular Console independent of the host OS installed Node version, if any.

**Comment by mrmeku** [comment]
I'm going to attempt to support this feature request via using the node instance bundled with electron / vscode rather than bundling a separate version our selves. That way its kept up to date. Additionally we are going to be adding support you to specify a path to a specific version of node you want to use (that's a seperate feature request but I thought I'd mention it to you)

**Comment by mrmeku** [comment]
We have decided to sunset our electron release of console so that we can better focus on high quality editor extension. That being the case I'm going to sadly close this bug with no plans to resolve the ask. 

We will move forward with allowing user's to specify their own node_path

**Comment by MrCroft** [comment]
@mrmeku is "to sunset" a poetic way to say "end of life" for the Electron release?
That's sad to hear. It feels so much nicer to have an independent/dedicated app, instead of being a tab in VSCode.
Also... even though I use VSCode 90% of the time (only sometimes switching to WebStorm for more difficult git stuff), maybe there are a lot of devs that don't necessarily use VSCode and use other IDEs.
