### ISSUE TITLE
allow npm commands from within angular console

### ISSUE THREAD

**Issue by Syntactual** [nrwl/angular-console#679]

**Comment by guillermoarellano** [comment]
Hi Josh,

A few more questions about this issue.

Are you looking for a terminal inside the Angular Console as your running a Schematic? Does the Task menu screen, which extracts the NPM scripts from your package.json, is too limiting? What use cases are you imagining? Let us know.

Thanks,
Guillermo

**Comment by Syntactual** [comment]
Was talking to Jeff today about being able to run npm install from the
angular console. I can own the issue and make a feature for it if you want
and make a PR. Basically I was doing a lunch and learn and was using
angular console but had to switch to terminal for npm commands. Was
thinking it would be nice to stay in the angular console the whole time. If
this is already possible then close the issue but I was under the
impression it wasn't possible yet.

**Comment by guillermoarellano** [comment]
Hi Josh,

I am not a contributor, just an interested coder. If Jeff already knows about the feature and its expected behavior, then run with it.

Bowing out,
Guillermo

**Comment by mrmeku** [comment]
We have decided to sunset our electron release of console so that we can better focus on high quality editor extension. That being the case I'm going to sadly close this bug with no plans to resolve the ask. 

The editors we are targetting (vscode / intellij) already have plugins to execute NPM tasks so we will leave that functionality to them
