### ISSUE TITLE
Nrwl Connect error messages

### ISSUE THREAD

**Issue by authenticgoods** [nrwl/angular-console#683]
Was prompted for an update, clicked on Nrwl connect sign up...entered a u/p clicked sign up then received the JS errors, which froze angular-console. 

![Capture](https://user-images.githubusercontent.com/10005024/57453762-d178e780-722c-11e9-9c9e-268292e4dc54.JPG)
![Capture2](https://user-images.githubusercontent.com/10005024/57453769-d473d800-722c-11e9-8242-a91b9719cdf0.JPG)
![Capture3](https://user-images.githubusercontent.com/10005024/57453772-d63d9b80-722c-11e9-8b90-9d2d5896bef5.JPG)

**Comment by mrmeku** [comment]
We have decided to sunset our electron release of console so that we can better focus on high quality editor extension. That being the case I'm going to sadly close this bug with no plans to resolve the ask. 

This problem does not seem to occur within the vscode extension so it might be worth trying that out
