### ISSUE TITLE
[vscode] menu not responding

### ISSUE THREAD

**Issue by pabloxn** [nrwl/angular-console#705]
Nothing happens when clicking on any of the entries in the sidebar menu. I have tried uninstalling and reinstalling and no change. Any ideas?

**Comment by peterblazejewicz** [comment]
In the VSCode, does the output show anything usefull? (CMD+SHIFT+U/CTRL+SHIFT+U)

**Comment by pabloxn** [comment]
No nothing is recorded at all - No response.

**Comment by djorgji** [comment]
Any updates on this one?

Like the original reporter, nothing happens when clicking on the sidebar menu.

Restarted/Reinstalled, nothing changed.

**Comment by methodbox** [comment]
I just opened this issue due to on a new install even the side-bar item isn't appearing and using the command palette to open it doesn't work, either. 
https://github.com/nrwl/angular-console/issues/725

This plugin appears to be dead in the water.

**Comment by peterblazejewicz** [comment]
To be clear, the Angular Console side bar is missing usual UI context menu icon and when its `navigation` option is disabled you could see nothing there:
![image](https://user-images.githubusercontent.com/14539/59553717-588e4d80-8f99-11e9-80f3-422b67105dfd.png)
To fix this right click on the panel and pick `navigation` option from context menu.
Just wanted to be sure that this is not you've experienced folks.

**Comment by methodbox** [comment]
> To be clear, the Angular Console side bar is missing usual UI context menu icon and when its `navigation` option is disabled you could see nothing there:
> ![image](https://user-images.githubusercontent.com/14539/59553717-588e4d80-8f99-11e9-80f3-422b67105dfd.png)
> To fix this right click on the panel and pick `navigation` option from context menu.
> Just wanted to be sure that this is not you've experienced folks.

I'm not clear what you mean by this. Where are you right-clicking?

I accidentally got the extension to work, though! 

- I disabled the extension because it wasn't working.
- I opened an Angular project, re-enabled it and it still wasn't working.
- I then right-clicked the extension and selected "Configure Extension Settings" and it magically started working.

I suspect something with it initializing inside VS Code settings isn't working, however I didn't find anything new in settings.json.

**Comment by Tyrannmisu** [comment]
I am having the exact same problem with VS Code 1.35.1.
Angular Consloe does not appear in the side panel and opening it from the command palette  does absolutely nothing.

**Comment by ammaarpatel99** [comment]
I'm having the same issue. I installed the extension on vscode but it does nothing. I've done everything I can think of but nothing happens

**Comment by methodbox** [comment]
I've tried this on my Mac now, too, same issue.

I've tried reinstalling all of the major past versions with no success. I'm going to guess this hasn't been tested with VS Code 1.35.x and something in VS Code has changed.

@nrwl @amandacu @ bcabanes @JamesHenry @jaysoo @jeffbcross @pabloxn @ZackDeRose I'm not sure who owns this but this plugin is effectively useless in VS Code at the moment; seems like kind of a big issue, since VS Code 1.35 released in May. I'm assuming it hasn't been working since then.

**Comment by methodbox** [comment]
It's possible these two are related: https://github.com/nrwl/angular-console/issues/718

**Comment by methodbox** [comment]
FWIW, I've noticed that the icon eventually magically appears if I open an Angular project. I've duplicated this in Windows and Mac multiple times.

I'm not sure if that's intended, but if it is, it should be changed; otherwise how would one use the plugin to generate a component, for example, in an empty project?

I suspect the plugin is somehow sniffing for Angular to be present, but I'm not sure that makes sense.

**Comment by mrmeku** [comment]
This should be fixed with our latest release. We now always show the angular console icon regarldess of whether we detect and angular workspace or not. If we do not detect one we allow you to access the file tree to locate an angular.json you'd like console to use. Sorry for the delay in fixing this issue
