### ISSUE TITLE
new workspace fail - windows

### ISSUE THREAD

**Issue by OzBob** [nrwl/angular-console#731]
windows stand alone installation of NgConsole.

Open.
New.
![image](https://user-images.githubusercontent.com/1796771/59977373-f1a90e00-9602-11e9-81a0-26cbd3c6c46b.png)

![image](https://user-images.githubusercontent.com/1796771/59977355-c2929c80-9602-11e9-9295-7a09998b3e69.png)

1. The error result is not Copy-able.
2. the error result window is hiding the right 3(?) characters, see the 2nd screenshot, the actual name of the log file is "2019-06-23T13_57_17_534Z-debug.log"

**Comment by peterblazejewicz** [comment]
can you run your VSCode as an Administrator just to see if that remove that problem on your setup?

**Comment by mrmeku** [comment]
I will ensure that even without admin permissions, workspace creation will work on windows for our next major release. Thanks for submitting the bug report, these really really help me

**Comment by mrmeku** [comment]
We have decided to sunset our electron release of console so that we can better focus on high quality editor extension. That being the case I'm going to sadly close this bug with no plans to resolve the ask. 

We will have a new workspace creation flow as part of our VSCode extension's November release. Apologies for the delay
