### ISSUE TITLE
Message: "Error launching WinPTY agent: ConnectNamedPipe failed: Windows error 232"

### ISSUE THREAD

**Issue by manudss** [nrwl/angular-console#789]
Hello, 

I have an error, when I try to run any command in Angular Console. 

Do you have an idea, of what could be the error :

![image](https://user-images.githubusercontent.com/1046806/62521185-748ecc80-b82f-11e9-80c6-679f32fc37b7.png)

**Comment by manudss** [comment]
it's Angular console 8.0.0

**Comment by mbriggs** [comment]
This is due to an issue with node-tty and the way console scripting is implemented on windows. There is a workaround where you whitelist the `winpty-agent.exe` in your AV program https://github.com/microsoft/node-pty/issues/208#issuecomment-465624603

@mrmeku maybe we should add instructions on how to do that to angularconsole.com?

**Comment by mbriggs** [comment]
@manudss just curious, did whitelisting in your anti-virus app solve this?

**Comment by manudss** [comment]
Hi, sorry i didn't answered. I was not able to whitelist in my antivirus. It was a company antivirus, where I cannot do anything. 
Althougth, I cannot resolve this issue.

**Comment by mbriggs** [comment]
Unfortunately, there is nothing we can do about it, as it is an issue with overzealous AV software. If you are using the vs.code plugin, we recently changed our strategy for running commands to script the vs.code terminal instead of going through node-pty. Hopefully that will work better for you!
