### ISSUE TITLE
Dry run doesn’t work in VS Code extension

### ISSUE THREAD

**Issue by SachinShekhar** [nrwl/angular-console#816]
When I stop typing in VS Code extension, it doesn't show dry-run output at all. On the same PC, standalone desktop app doesn't have problem showing dry-run output.

**Comment by mrmeku** [comment]
@SachinShekhar What platform are you using? The dry run results should present themselves to you in the native VSCode terminal with our 8.1.0 release yesterday. 

But the dry run resuls only show up once all required flags have been specified. I think I'll make the dry run results show up immediately so that the UX is more clear. It could be that a required flag was left out so that the dry run results just never showed up

Is it possible that they are showing up, but they were missed? Could you post a screenshot of what you do see? Is it possible you missed a required flag?

Thanks so much for filing the issue and thanks in advance for any info you can get me

**Comment by mohijalili** [comment]
Same here. i can't see the dry run results show up immediately.

OS: Ubuntu 19.04
VSCode version : 1.37.1

I got this error on terminal:

```
Executing task: /home/mohi/projects/monorepo/node_modules/.bin/ng generate @nrwl/angular:library --dry-run --no-interactive <

Cannot read property 'replace' of undefined
The terminal process terminated with exit code: 1
```

**Comment by SachinShekhar** [comment]
@mrmeku I reported my old experience. I just installed Angular Console extension again and it has got way better. I can now see dry-run result in the VS Code terminal within reasonable time.
Thanks.
