### ISSUE TITLE
Make Generate context menu cleaner

### ISSUE THREAD

**Issue by SachinShekhar** [nrwl/angular-console#817]
When I click Generate button next to my apps or libs, Angular Console shows everything it can generate. This bloats the menu and may confuse new developers. For example, what has generating an application to do with a lib? To see all available options, we can certainly click Generate button on the left vertical bar.

Please, clean up the Generate context menu.

**Comment by mrmeku** [comment]
@SachinShekhar You're in luck, that is exactly the feature we are focusing on for our October release.

Here is a short list of things I think will help

1) When you click generate from the projects screen we need to filter the schematics to those that let you specify a project. If a schematic doesn't let you specify a project, then we exclude it from the list

2) Putting commonly used / favorited schematics at the top of the list. Typically, when targetting a project people want to generate a component or a service more often than not. By default, we should make these at the top of the list. Additionally, we should allow you to mark your favorite schematics so they also appear at the top of the list

3) Integrating with VSCode's native quick select menu. I want `ng generate` to be accessible via the command palate. When you access `ng generate` via the palate, we should use VSCode's native selection UI which has better UX than the UI console has currently

@SachinShekhar If you have any other UX tweaks you can think of that would make the experience nicer, please shout them out! Otherwise the above are what I'm planning on
