### ISSUE TITLE
Angular Console opens a blanc window after update (Mac OS)

### ISSUE THREAD

**Issue by baunov** [nrwl/angular-console#827]
Hi, first of all - great product. Very useful especially for full-stack apps.
I've just updated Angular Console to v.8.1.0. And instantly after update it now shows a blanc screen when opened. 
I'm on MacOS Mojave 10.14.2.

Just in case I restarted OS but this behavior is still there.

Here's how Angular Console looks now when opened:
<img width="802" alt="blanc Angular Console" src="https://user-images.githubusercontent.com/54023692/64552169-5c82ff00-d33f-11e9-81d7-66029e211e62.png">

-------
EDIT
-------

I've just found a way to make it work. Basically just needed to do View -> Reload (Command + R). It's now back. But by itself, it might be an issue.

**Comment by sh33dafi** [comment]
I'm having the same issue,
the view > reload works until I restart angular console
I checked the console in dev tools, nothing there

**Comment by mrmeku** [comment]
We have decided to sunset our electron release of console so that we can better focus on high quality editor extension. That being the case I'm going to sadly close this bug with no plans to resolve the ask.

I apologize that our last release was buggy on Mac OS everyone. That really stinks. But with our new engineering resources we've freed up by dropping electron support the vscode variant of console will have a high degree of polish from this point forward
