### ISSUE TITLE
Plugin menu broken after VSCode upgrade

### ISSUE THREAD

**Issue by alejandro-a** [nrwl/angular-console#834]
As mentioned the menu looks broken.
Is that normal?
![Schermata 2019-09-13 alle 16 16 59](https://user-images.githubusercontent.com/11943746/64873014-87739880-d648-11e9-80e7-251d0a7b63a8.png)

This happened after the last VSCode upgrade, is there a way to fix this part?

**Comment by luejerry** [comment]
Not really a fix, but downgrading the extension to version 8.1.1 restored the old menu for me.

**Comment by mrmeku** [comment]
@beamkatana This change was intentional, but I understand that since you're filing an issue that we might have not addressed how you use console.

The new navigation pane layout makes it so that you choose an action you want to perform with the cli and then you select a project from a quick select menu

Below we have an angular json explorer which lists all of your projects as our projects screen used to

I was hoping the combination of these two features would give feature parity, but I'm interested in your thoughts here. What do you feel is missing? Was the change just confusing or do you really miss the old workflow?

**Comment by JakeAi** [comment]
I also really liked the old way. Can we have an option to use both? Randomly opening your IDE one day and suddenly everything is "gone" was kind of an issue.  It also wasn't working correctly on my windows machine, but works fine on MacOS. It also made me feel as if my project was broken somehow. I created a whole new mono repo just to see it didn't make a difference.

**Comment by ChrisColeTech** [comment]
huge step back design-wise.

**Comment by nixallover** [comment]
@JakeAi @ChrisColeTech Sorry to hear you're dissatisfied with the design changes, and I understand your sentiments on the change being jarring. We're aiming to have the Angular Console VS Code extension feel more integrated with the editor and run faster, among other improvements. Naturally, some of the changes we're basing on how we use Angular Console in our own projects. We'd love to hear more about the specifics of how you use the extension, and what is missing from the updated version, so we can integrate that feedback into our design discussions and make it a better tool for you as well.

**Comment by JakeAi** [comment]
@nixallover I’ll just use Angular Console stand-alone. Thanks.

**Comment by dallasclymer** [comment]
I liked the ond way too.

**Comment by alejandro-a** [comment]
> @beamkatana This change was intentional, but I understand that since you're filing an issue that we might have not addressed how you use console.
> 
> The new navigation pane layout makes it so that you choose an action you want to perform with the cli and then you select a project from a quick select menu
> 
> Below we have an angular json explorer which lists all of your projects as our projects screen used to
> 
> I was hoping the combination of these two features would give feature parity, but I'm interested in your thoughts here. What do you feel is missing? Was the change just confusing or do you really miss the old workflow?

For me the old one was more user friendly and easy to explain to someone else in my team who is not familiar with angular cli.

The new one is faster to use and is integrated like vscode command palette. Dedicated panel seems useless if used only for this purpose instead keyboard shortcuts would have been enough.

I think it would be better if you would integrate these cli commands separately (like keyboard shortcuts) and continue improving the old UI

**Comment by hernebrink** [comment]
Sorry, have to ask. Yesterday I was able to generate libraries, appliactions etc from within angular console pane. Today, nothing happens when I click the buttons e.g. generate, serve, test etc. Is that by design now, or am I missing something? The same workspace works fine in the standalone windows application for generating and running npm scripts etc. Thanks.

**Comment by jaysoo** [comment]
Thank for all the feedback folks! We're not going to support the old UX or the desktop app moving forward.

You're always welcome to download the desktop/standalone app, but we're not going to be making future releases of it, apart from any minor fixes. https://github.com/nrwl/angular-console/releases

For bugs or issues with the updated UX, can you please open a new issue? Thanks!
