### ISSUE TITLE
After creating a new workspace, "Generate" button is disabled

### ISSUE THREAD

**Issue by jcantais** [nrwl/angular-console#856]
After I create a new workspace, I can see my new app at "Projects" along with "Generate" and "Run" buttons, but the "Generate" button is disabled.

**Comment by nixallover** [comment]
@jcantais Thanks for reporting this. Are you using the desktop app? Are you on Windows or Mac?

**Comment by jcantais** [comment]
Yes, I am using the desktop app on Windows

**Comment by jaysoo** [comment]
@jcantais Can you try using the vscode extension instead? 
https://marketplace.visualstudio.com/items?itemName=nrwl.angular-console

We have removed support for the desktop app in favor of making the vscode extension more enjoyable and robust. As a result we won't be actively maintaining the desktop app.

I'm going to close this issue since it's related to desktop app.
