### ISSUE TITLE
A progress bar should be shown while opening up a workspace, as the process takes time

### ISSUE THREAD

**Issue by debashish2014** [nrwl/angular-console#877]
A progress bar should be shown while opening up a workspace, as the process takes time

**Comment by mrmeku** [comment]
@debashish2014 We had a bug which was making opening a workplace take a significant amount of time rather than be instantaneous. I fixed that bug as part of  this PR (https://github.com/nrwl/angular-console/pull/881/files#diff-057411b779dce09ed411b50346f36279R202)

We were caching node_modules metadata as part of syncronous action. But now we've moved it to a settimeout so that it won't block switching your workspace.

I'll close this issue once our next release is out with the fix :)
