### ISSUE TITLE
Rebranding and make it compatible with workspace.json :-) ?

### ISSUE THREAD

**Issue by iangregsondev** [nrwl/angular-console#894]
Hi,

I was wondering if you have plans to make it compatible with workspace.json (NX) which technically is an angular.json file but named workspace.json for use by the nx cli.

And then i suppose a rebranding would be needed - from angular console to NX console :-) ?

Would love to hear what plans you have and when it will happen 

Right now to use angular console, i have to ensure i use an angular.json and NOT a workspace.json

Thanks in advance

**Comment by jaysoo** [comment]
@iangregsondev Great question! We're planning support for nx workspaces in Angular Console (e.g. `workspace.json`) but no definite release date yet. 

Rebranding is a different discussion, and we don't have any plans to rebrand yet because we're focused on making the experience as solid as possible for Angular projects before branching out.

**Comment by iangregsondev** [comment]
Ok - thanks for your input. I look forward to it.. At the moment, i will continue with the angular.json workspaces...

thanks.
