### ISSUE TITLE
Where is angular console app for Mac ? 

### ISSUE THREAD

**Issue by kapik** [nrwl/angular-console#901]
Hey ! 

I just realized that you can no longer download the app for Mac from https://angularconsole.com/ 😱 
Is this a mistake or are you no longer considering app?

**Comment by jaysoo** [comment]
Hi @kapik, we had to end support for the electron app due to lack of resources to maintain multiple platforms. If you do use VSCode, please check out our revamped extension--we made the integration much more seamless and robust.

For more information about the new release, see this blog post: https://github.com/nrwl/angular-console/releases.

---

If you still want to use the desktop app, you can find them in the releases page. However, we will no longer make additional releases beyond small patches.

https://github.com/nrwl/angular-console/releases
